# Generated by Django 3.2.20 on 2025-02-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_dataupdatesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupdatesettings',
            name='term',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], default='Fall', help_text='Select either Spring or Fall term', max_length=10),
        ),
    ]
